name: Freeswitch CI

on:
  push:
    branches: [ v1.10 ]
  pull_request:
    branches: [ v1.10 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
