name: Freeswitch CI

on:
  push:
    branches: [ v1.10 ]
  pull_request:
    branches: [ v1.10 ]

jobs:

  cleaner:
    runs-on: [self-hosted, freeswitch]
    steps:
      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
          
  build:
    needs: [cleaner]
    runs-on: [self-hosted, freeswitch]
    if: "!contains(github.event.head_commit.message, 'version bump to')"

    #src/mod/applications/mod_fifo_extended/.libs/mod_fifo_extended.so
    steps:
    - uses: actions/checkout@v2

    - name: bootstrap
      run: ./bootstrap.sh
      
    - name: configure
      run: ./configure
      
    - name: make mod_fifo_extended
      run: make mod_fifo_extended

    - name: Bump version and push tag
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        version-file: './mod_fifo_extended.version'
        github-token: ${{ secrets.github_token }}
        git-message: 'version bump to: {version}'
        preset: 'angular'
        tag-prefix: 'mod_fifo_extended-'
        skip-on-empty: 'false'

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      name: ${{ steps.changelog.outputs.tag }}
      tag_name: ${{ steps.changelog.outputs.tag }}
      with:
          files: src/mod/applications/mod_fifo_extended/.libs/mod_fifo_extended.so
      env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
